### ISSUE TITLE
hacktoberfest-doubt

### ISSUE THREAD

**Issue by GeneralChauhan** [AdamSlater/calimental#2]
What is this project for?

**Comment by GeneralChauhan** [comment]
i want to contribute

**Comment by AdamSlater** [comment]
It’s going to be an incremental clicker game. But instead of typical resource gathering, it will be exercise based. 

Regards,
    Adam

**Comment by AdamSlater** [comment]
See: https://i.imgur.com/ylNBlwb.png for example exercise progression
See: https://orteil.dashnet.org/cookieclicker/ for example incremental/idle game
